using System;
using UnityEngine;

public class Descriptions : MonoBehaviour
{
    // Spirit Archer:
    // Ability: Gain 100% Attackspeed. Attacks bounce between enemys.
    // Passive: 10% chance to extract light on hit.
    // Passive Stats: +50% Range; +100% Attackspeed;
    // TODO:
    // Spirit Bow:
    // Subtitle:
    // Lore:A group of Spirits fled to the top of remainig trees. In order to defend themself, they crafted this bow out of vines, twigs and leaves
    // Special Ability: 5% Chance to gain 20% Attackspeed on hit
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
    // TODO:
}
